### ISSUE TITLE
Update the review command to diff against upstream base_branch rather than just base_branch

### ISSUE THREAD

**Issue by DiannaHohensee** [mongodb/server-workflow-tool#35] opened 2019-06-07 21:06 UTC
Max suggested using "--rev {ticket_conf.base_branch}@{{upstream}}..." here https://github.com/mongodb/server-workflow-tool/blob/c4fac98001aeb9a130c32c610a557a0efaa1c59d/serverworkflowtool/tasks.py#L187 instead of "--rev {ticket_conf.base_branch}..." to fix a problem where if the work branch is being rebase from remote origin master, the CR diff will contain the diff between the work branch and the out of date local master branch. This change fixes that problem.

**Comment by guoyr** [comment] 2019-06-09 16:43
Thanks @visemet and Dianna for the suggestion. I've incorporated it into #36.

That said, I think the root cause is user error and my PR will not fix the problem. The workflow tool [updates the base branch](https://github.com/mongodb/server-workflow-tool/blob/c4fac98001aeb9a130c32c610a557a0efaa1c59d/serverworkflowtool/tasks.py#L64) when  creating a new feature branch, so the base branch should never be behind.

The most likely reason for the base branch to be behind is for the user to manually run `git pull --rebase origin master` on the feature branch. People shouldn't do this regardless of whether they're using the workflow tool or not because it makes Reitveld pick up unrelated changes.

The workflow tool intentionally does not allow rebasing a feature branch until the very end, when it is ready to be squashed and merged with upstream. But of course it can't prevent people from running git manually outside of it.

**Closed by guoyr** 2019-06-09 16:43 UTC

**Comment by milkie** [comment] 2019-06-10 13:33
I personally would find it very difficult to never rebase any work until after the final code review is approved.  What if the rebasing requires material changes?  They ought to again be code reviewed..

**Comment by visemet** [comment] 2019-06-10 13:35
Rebasing between patch sets on the code review will cause the intra-diff to show extra changes that were made to those modified files. As a policy, I thought we had discouraged rebasing unless absolutely necessary. I personally don't rebase my branch for code reviews but then rebase on a separate branch whenever I put up an Evergreen patch build.

**Comment by milkie** [comment] 2019-06-10 13:37
I don't find a rebase patch in a CR all that onerous.  It's easily ignored when done as a separate patch.  I'm not sure about policy; I think it has just been discouraged to do a rebase and serve up new changes in the same patch.
